name: Run Script

on:
  schedule:
    - cron: '*/15 * * * *' # Запуск скрипта каждые 15 минут
  workflow_dispatch: # Возможность запуска вручную через интерфейс GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Обновлено до v3

    - name: Set up Python
      uses: actions/setup-python@v3  # Обновлено до v3
      with:
        python-version: '3.x'

    - name: Install Chrome Driver
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
        wget -N https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip -P ~/
        unzip ~/chromedriver_linux64.zip -d ~/
        sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
        sudo chown root:root /usr/local/bin/chromedriver
        sudo chmod 0755 /usr/local/bin/chromedriver

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests selenium python-telegram-bot

    - name: Run script
      run: python telegram_message_copier.py
